# -*- coding: utf-8 -*-
"""Small FBX 7.4 binary encoder for the exporter generated by this project.

Blender intentionally does not import ASCII FBX.  The animation pipeline keeps
its readable scene builder and passes the generated subset through this module
to produce a real Kaydara binary FBX without requiring Autodesk's SDK or a
Blender installation on the user's machine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import csv
import io
import re
import struct
import zlib
from typing import Any, List


FBX_VERSION = 7400
HEADER_MAGIC = b"Kaydara FBX Binary  \x00\x1a\x00"
FOOTER_MAGIC = bytes.fromhex("fabcab09d0c8d466b176fb831cf7267e")
FOOTER_TAIL = bytes.fromhex("f85a8c6adef5d97eece90ce3758f290b")
FILE_ID = bytes.fromhex("28b32aebb624ccc2bfc8b02aa92bfcf1")
NULL_RECORD = b"\x00" * 13

_OBJECT_NODES = {
    "Model", "NodeAttribute", "Geometry", "Deformer", "AnimationStack",
    "AnimationLayer", "AnimationCurveNode", "AnimationCurve", "Pose",
}
_INT64_SCALARS = {
    "LocalStart", "LocalStop", "ReferenceStart", "ReferenceStop",
}
_FLOAT_ARRAYS = {"KeyValueFloat", "KeyAttrDataFloat"}
_DOUBLE_ARRAYS = {
    "Vertices", "Normals", "Weights", "Transform", "TransformLink",
    "TransformAssociateModel", "Matrix",
}
_INT64_ARRAYS = {"KeyTime"}
_ARRAY_LINE = re.compile(
    r'^\s*([A-Za-z0-9_]+):\s*\*\d+\s*\{\s*a:\s*(.*?)\s*\}\s*$'
)


@dataclass
class Property:
    code: str
    value: Any


@dataclass
class Element:
    name: str
    properties: List[Property] = field(default_factory=list)
    children: List["Element"] = field(default_factory=list)


def _split_values(source: str) -> List[Any]:
    if not source.strip():
        return []
    values = next(csv.reader(io.StringIO(source), skipinitialspace=True))
    result: List[Any] = []
    for value in values:
        value = value.strip()
        if value == "T":
            result.append(True)
        elif value == "F":
            result.append(False)
        else:
            try:
                if any(mark in value.lower() for mark in (".", "e")):
                    result.append(float(value))
                else:
                    result.append(int(value))
            except ValueError:
                result.append(value)
    return result


def _binary_object_name(value: str) -> str:
    if "::" not in value:
        return value
    kind, name = value.split("::", 1)
    # Binary FBX stores this in the opposite order from the ASCII spelling:
    # ``Name NUL SOH Class``.  Blender validates the class suffix strictly.
    return f"{name}\x00\x01{kind}"


def _scalar_properties(node_name: str, values: List[Any]) -> List[Property]:
    result: List[Property] = []
    property_kind = str(values[1]).lower() if node_name == "P" and len(values) > 1 else ""
    for index, value in enumerate(values):
        if isinstance(value, bool):
            code = "C"
        elif isinstance(value, str):
            code = "S"
            if node_name in _OBJECT_NODES and index == 1:
                value = _binary_object_name(value)
        elif isinstance(value, float):
            code = "D"
        elif isinstance(value, int):
            if (node_name in _OBJECT_NODES and index == 0) or (
                node_name == "C" and index > 0
            ) or node_name in _INT64_SCALARS:
                code = "L"
            elif node_name == "P" and index >= 4 and (
                property_kind == "ktime" or "time" in property_kind
            ):
                code = "L"
            elif node_name == "P" and index >= 4 and property_kind not in {
                "int", "integer", "enum", "bool"
            }:
                code = "D"
                value = float(value)
            else:
                code = "I"
        else:
            raise TypeError(f"Unsupported FBX scalar {value!r}")
        result.append(Property(code, value))
    return result


def parse_ascii_scene(source: str) -> Element:
    """Parse the deliberately small ASCII subset emitted by AnimationPipeline."""
    root = Element("")
    stack = [root]
    for line_number, raw_line in enumerate(source.splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith(";"):
            continue
        if line == "}":
            if len(stack) == 1:
                raise ValueError(f"Unexpected closing brace at line {line_number}")
            stack.pop()
            continue

        array_match = _ARRAY_LINE.match(line)
        if array_match:
            name, values_source = array_match.groups()
            values = _split_values(values_source)
            if name in _FLOAT_ARRAYS:
                code = "f"
            elif name in _DOUBLE_ARRAYS:
                code = "d"
            elif name in _INT64_ARRAYS:
                code = "l"
            else:
                code = "i"
            stack[-1].children.append(Element(name, [Property(code, values)]))
            continue

        empty_block = line.endswith("{}")
        opens_block = line.endswith("{") or empty_block
        content = line[:-2].rstrip() if empty_block else line[:-1].rstrip() if opens_block else line
        if ":" not in content:
            raise ValueError(f"Malformed FBX line {line_number}: {line}")
        name, values_source = content.split(":", 1)
        element = Element(name.strip(), _scalar_properties(name.strip(), _split_values(values_source)))
        stack[-1].children.append(element)
        if opens_block and not empty_block:
            stack.append(element)
    if len(stack) != 1:
        raise ValueError("Unclosed FBX block")
    return root


def _encode_property(prop: Property) -> bytes:
    code = prop.code
    value = prop.value
    if code == "C":
        payload = struct.pack("<?", bool(value))
    elif code == "I":
        payload = struct.pack("<i", int(value))
    elif code == "L":
        payload = struct.pack("<q", int(value))
    elif code == "F":
        payload = struct.pack("<f", float(value))
    elif code == "D":
        payload = struct.pack("<d", float(value))
    elif code in ("S", "R"):
        data = value.encode("utf-8") if isinstance(value, str) else bytes(value)
        payload = struct.pack("<I", len(data)) + data
    elif code in ("i", "l", "f", "d"):
        fmt = {"i": "i", "l": "q", "f": "f", "d": "d"}[code]
        values = list(value)
        raw = struct.pack(f"<{len(values)}{fmt}", *values) if values else b""
        if len(raw) > 128:
            data = zlib.compress(raw, 1)
            payload = struct.pack("<III", len(values), 1, len(data)) + data
        else:
            payload = struct.pack("<III", len(values), 0, len(raw)) + raw
    else:
        raise TypeError(f"Unsupported FBX property code {code!r}")
    return code.encode("ascii") + payload


def _write_element(buffer: bytearray, element: Element, is_last: bool) -> None:
    start = len(buffer)
    name = element.name.encode("utf-8")
    encoded_properties = [_encode_property(prop) for prop in element.properties]
    property_data = b"".join(encoded_properties)
    buffer.extend(b"\x00" * 12)
    buffer.append(len(name))
    buffer.extend(name)
    buffer.extend(property_data)
    if element.children:
        for index, child in enumerate(element.children):
            _write_element(buffer, child, index == len(element.children) - 1)
        buffer.extend(NULL_RECORD)
    elif (not element.properties and not is_last) or element.name in {
        "AnimationStack", "AnimationLayer"
    }:
        buffer.extend(NULL_RECORD)
    struct.pack_into(
        "<III", buffer, start, len(buffer), len(element.properties), len(property_data)
    )


def encode_binary_scene(source: str, version: int = FBX_VERSION) -> bytes:
    root = parse_ascii_scene(source)
    if not any(child.name == "FileId" for child in root.children):
        insert_at = 1 if root.children else 0
        root.children[insert_at:insert_at] = [
            Element("FileId", [Property("R", FILE_ID)]),
            Element("CreationTime", [Property("S", "1970-01-01 10:00:00:000")]),
        ]
    output = bytearray(HEADER_MAGIC)
    output.extend(struct.pack("<I", version))
    for index, child in enumerate(root.children):
        _write_element(output, child, index == len(root.children) - 1)
    output.extend(NULL_RECORD)
    output.extend(FOOTER_MAGIC)
    output.extend(b"\x00" * 4)
    padding = (-len(output)) % 16 or 16
    output.extend(b"\x00" * padding)
    output.extend(struct.pack("<I", version))
    output.extend(b"\x00" * 120)
    output.extend(FOOTER_TAIL)
    return bytes(output)


def write_binary_fbx(source: str, output_path: str) -> None:
    with open(output_path, "wb") as handle:
        handle.write(encode_binary_scene(source))
